import { FormEvent, useState } from "react";
import { CheckCircle2, KeyRound, LockKeyhole, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

export default function Activate() { const { isAuthenticated } = useAuth(); const [code, setCode] = useState(""); const [done, setDone] = useState(false); const activation = trpc.subscription.activate.useMutation({ onSuccess: () => setDone(true) }); function submit(e: FormEvent) { e.preventDefault(); activation.mutate({ code: code.trim().toUpperCase() }); } if (!isAuthenticated) return <div className="mx-auto max-w-xl px-5 py-24 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-[#f0eaff] text-[#8f6ee8]"><LockKeyhole /></div><h1 className="mt-6 text-4xl font-black">سجّل الدخول أولًا</h1><p className="mt-3 leading-8 text-[#81768c]">يجب ربط الاشتراك بحسابك حتى لا يمكن مشاركة الكود مع مستخدم آخر.</p><Button onClick={() => startLogin()} className="mt-7 rounded-xl bg-[#8f6ee8]">تسجيل الدخول</Button></div>; return <div className="mx-auto max-w-xl px-5 py-16"><div className="rounded-[2rem] border border-[#eee6f7] bg-white p-8 text-center shadow-sm"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-[#f0eaff] text-[#8f6ee8]"><KeyRound /></div><h1 className="mt-6 text-4xl font-black">تفعيل اشتراكك</h1><p className="mt-3 leading-8 text-[#81768c]">أدخل Activation Code الذي استلمته من إدارة مرقاب.</p>{done ? <div className="mt-8 rounded-2xl bg-[#eaf9f1] p-5 text-[#378d6b]"><CheckCircle2 className="mx-auto" /><div className="mt-2 font-black">تم تفعيل اشتراكك بنجاح</div><div className="mt-1 text-sm">يمكنك الآن استخدام مزايا الباقة.</div></div> : <form onSubmit={submit} className="mt-8 space-y-4"><Input value={code} onChange={e => setCode(e.target.value)} placeholder="ILP-XXXX-XXXX-XXXX-XXXX" className="h-14 rounded-xl bg-[#fbf9ff] text-center font-mono text-lg tracking-wider" /><Button disabled={activation.isPending || code.length < 10} className="h-14 w-full rounded-xl bg-[#8f6ee8]">{activation.isPending ? "جارٍ التحقق…" : "تفعيل الاشتراك"}</Button>{activation.error && <p className="text-sm font-semibold text-[#c36f9d]">{activation.error.message}</p>}</form>}<div className="mt-7 flex items-center justify-center gap-2 text-xs text-[#95899d]"><ShieldCheck size={15} className="text-[#61b691]" /> الكود لمرة واحدة ومربوط بحسابك</div></div></div> }
