import { Link, useLocation } from "wouter";
import { Gauge, Menu, Search, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";

const navItems = [["الرئيسية", "/"], ["تحليل حساب", "/search"], ["المراقبة", "/dashboard"], ["مقارنة المتابعين", "/followers-import"], ["المقارنة", "/compare"], ["الباقات", "/pricing"]] as const;

export default function SiteShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false); const [location] = useLocation(); const { isAuthenticated, user, logout } = useAuth();
  return <div className="min-h-screen bg-[#f7f7f4] text-[#20241f]">
    <header className="sticky top-0 z-50 border-b border-[#dedfd8]/90 bg-[#f7f7f4]/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-3" onClick={() => setOpen(false)}><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-[#2d3a30] text-[#f1d4bf] shadow-lg shadow-[#2d3a3020]"><span className="text-xl font-black">م</span></span><span className="text-2xl font-black tracking-[-.05em] text-[#2d3a30]">مرقاب</span></Link><nav className="hidden items-center gap-7 lg:flex">{navItems.map(([label, href]) => <Link key={href} href={href} className={`text-sm font-bold transition-colors hover:text-[#55785a] ${location === href ? "text-[#55785a]" : "text-[#6d756b]"}`}>{label}</Link>)}</nav><div className="hidden items-center gap-3 lg:flex">{isAuthenticated ? <><Link href="/dashboard" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-[#55785a] hover:bg-[#e9eee7]"><Gauge size={17} />لوحتي</Link><Button variant="outline" className="rounded-xl border-[#cfd7cc]" onClick={() => logout()}>خروج</Button></> : <Button onClick={() => startLogin()} className="rounded-xl bg-[#2d3a30] px-5 text-white shadow-lg shadow-[#2d3a3020] hover:bg-[#405545]">دخول الحساب</Button>}</div><button aria-label="فتح القائمة" className="rounded-xl p-2 hover:bg-[#e9eee7] lg:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-[#dedfd8] bg-[#f7f7f4] px-5 py-4 lg:hidden"><div className="grid gap-2">{navItems.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="rounded-xl px-3 py-3 font-bold text-[#596258] hover:bg-[#e9eee7]">{label}</Link>)}<div className="mt-2 border-t border-[#dedfd8] pt-3">{isAuthenticated ? <div className="flex items-center justify-between"><span className="text-sm font-semibold">{user?.name ?? "حسابك"}</span><Button variant="outline" className="rounded-xl border-[#cfd7cc]" onClick={() => logout()}>خروج</Button></div> : <Button onClick={() => startLogin()} className="w-full rounded-xl bg-[#2d3a30] text-white">دخول الحساب</Button>}</div></div></div>}</header>
    <main>{children}</main>
    <footer className="mt-10 border-t border-[#dedfd8] bg-[#f7f7f4]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-[#7b8378] md:flex-row md:items-center md:justify-between lg:px-8"><div><span className="font-black text-[#2d3a30]">مرقاب</span> · قراءة أوضح للحسابات العامة.</div><div className="flex gap-5"><Link href="/privacy" className="hover:text-[#55785a]">الخصوصية</Link><Link href="/terms" className="hover:text-[#55785a]">الشروط</Link><Link href="/about" className="hover:text-[#55785a]">عن مرقاب</Link></div></div></footer>
  </div>;
}
